name: CI/CD - Develop

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1 - Clonar o código
      - name: Checkout código
        uses: actions/checkout@v4

      # 2 - Cache do Maven
      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}

      # 3 - Configurar JDK 11
      - name: Configurar JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      # 4 - Dar permissão ao mvnw
      - name: Dar permissão de execução ao mvnw
        run: chmod +x mvnw    

      # 5 - Build e Testes
      - name: Build e Testes
        run: ./mvnw clean install -B

      # 6 - Build da imagem Docker
      - name: Build Docker Image
        run: |
          docker build -t myapp-develop:latest .

      # 7 - Login no Docker Hub
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 8 - Push da imagem Docker
      - name: Push Docker Image
        run: |
          docker tag myapp-develop:latest ${{ secrets.DOCKER_USERNAME }}/myapp-develop:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp-develop:latest

      # 9 - Deploy em Homologação
      - name: Deploy em Homologação
        if: github.ref == 'refs/heads/develop'
        run: |
          echo "Deploy do container em ambiente de homologação..."
