name: CI/CD - Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      - name: Test API
        run: echo "Testando API..."

  test-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      - name: Test UI
        run: echo "Testando UI..."

  build-api:
    runs-on: ubuntu-latest
    needs: [test-api]
    steps:
      - name: Build API
        run: echo "Buildando API..."

  build-ui:
    runs-on: ubuntu-latest
    needs: [test-ui]
    steps:
      - name: Build UI
        run: echo "Buildando UI..."

  docker-api:
    runs-on: ubuntu-latest
    needs: [build-api]
    steps:
      - name: Docker API
        run: echo "Buildando imagem Docker da API..."

  docker-ui:
    runs-on: ubuntu-latest
    needs: [build-ui]
    steps:
      - name: Docker UI
        run: echo "Buildando imagem Docker da UI..."

  deploy:
    runs-on: ubuntu-latest
    needs: [docker-api, docker-ui]
    steps:
      - name: Deploy
        run: echo "Deploy final..."